server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rolemodel
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
