server:
  port: 8981
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_rolemodel
    username: postgres
    password: password
    dbcp2:
      default-schema: public
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl: update
  flyway:
    locations: classpath:/db/migration, classpath:prod/db/migration